### ISSUE TITLE
Handle re-setting of simulation-time more gracefully

### ISSUE THREAD

**Issue by jbohren** [ros/geometry2#43]
Currently, buffer_core [issues a warning](https://github.com/ros/geometry_experimental/blob/hydro-devel/tf2/src/buffer_core.cpp#L260) when "old data" is published when a simulation clock source like gazebo gets re-set. In the context of simulation time, if the `/clock` topic also goes backwards in time, then this should be considered neither an error or a warning.

What would be the right way to make buffer_core re-set when tf_ros detects a simulation time reset?

**Comment by trainman419** [comment]
+1 to getting this fixed.

**Comment by tfoote** [comment]
Fixed in 619a1329854d8e6fcc78c576a53594f2caadf383 ported forward from #68

**Comment by furushchev** [comment]
Hi, was this already fixed on indigo?
I still have the same problem when executing `rosbag play` with option `--loop --clock`.

```bash
Warning: TF_OLD_DATA ignoring data from the past for frame odom at time 1.49284e+09 according to authority unknown_publisher
Possible reasons are listed at http://wiki.ros.org/tf/Errors%20explained
         at line 273 in /tmp/binarydeb/ros-indigo-tf2-0.5.15/src/buffer_core.cpp
Warning: TF_OLD_DATA ignoring data from the past for frame odom at time 1.49284e+09 according to authority unknown_publisher
Possible reasons are listed at http://wiki.ros.org/tf/Errors%20explained
         at line 273 in /tmp/binarydeb/ros-indigo-tf2-0.5.15/src/buffer_core.cpp
Warning: TF_OLD_DATA ignoring data from the past for frame odom at time 1.49284e+09 according to authority unknown_publisher
Possible reasons are listed at http://wiki.ros.org/tf/Errors%20explained
         at line 273 in /tmp/binarydeb/ros-indigo-tf2-0.5.15/src/buffer_core.cpp
Warning: TF_OLD_DATA ignoring data from the past for frame base_footprint_wheel at time 1.49284e+09 according to authority unknown_publisher
Possible reasons are listed at http://wiki.ros.org/tf/Errors%20explained
         at line 273 in /tmp/binarydeb/ros-indigo-tf2-0.5.15/src/buffer_core.cpp
Warning: TF_OLD_DATA ignoring data from the past for frame base_footprint at time 1.49284e+09 according to authority unknown_publisher
Possible reasons are listed at http://wiki.ros.org/tf/Errors%20explained
         at line 273 in /tmp/binarydeb/ros-indigo-tf2-0.5.15/src/buffer_core.cpp
Warning: TF_OLD_DATA ignoring data from the past for frame odom at time 1.49284e+09 according to authority unknown_publisher
Possible reasons are listed at http://wiki.ros.org/tf/Errors%20explained
         at line 273 in /tmp/binarydeb/ros-indigo-tf2-0.5.15/src/buffer_core.cpp
```

```bash
rosversion tf2
0.5.15
```

CC: @tfoote

**Comment by furushchev** [comment]
I manually compiled entire `geometry2` package from source, and it now clears cache without any problem.
Strange...

```bash
cd /path/to/catkin_ws/src/
wstool set -u ros/geometry2 https://github.com/ros/geometry2 -v 0.5.15
catkin b geometry2
source ../devel/setup.bash
```

**Comment by tfoote** [comment]
I don't know of any differences re source vs binary. If you can provide a simple example I can try to reproduce.

**Comment by pryre** [comment]
No to dig up an old issue, but I think I have an example that may help with this. From what I have found, it may be linked to not using a listener with the buffer. Currently running on Kinetic: `rosversion tf2 - 0.5.17`

My setup involves interfacing with a `tf2_ros::Buffer` manually, using `setTransform(...)` to push data from a pose message into the buffer, and `lookupTransform("...", "...", ros::Time(0))` to pull the latest common pose back out.

Issue seems to arise when trying to set a transform that is older than the buffers `cache_time`. I have a bag file on loop putting out a clock message, and use the `-u` flag on rosbag to adjust the replay duration. As soon as the loop performs a reset that's longer than the 10 second default, I get `Warning: TF_OLD_DATA ignoring from the past...`. As soon as the clock is back within the `cache_time` bounds, warnings stop and behavior is as normal.

Example:
- Set rosbag too loop data with a duration of 15 seconds and publish clock
- Set `use_sim_time` to true
- Start node using buffer as described with `cache_time` left at the default 10 seconds
- No errors will occur until clock reset
- Errors will stop at exactly t=5 seconds, when clock time is back within the cache time range (from the last recorded time on the cache which is 15 seconds)

Adjusting either the rosbag duration to be less than the `cache time`, or extending the `cach_time` to be longer than the loop duration causes the set data to behave as expected.

I have a feeling that this may be "intended behavior" if not using a tf2 listener, as perhaps the listener is the one that is managing clearing the cache.

**Comment by tfoote** [comment]
Yes that is expected behavior if you're just using a buffer it only expects time to progress forward, the linked commit above is specific to the listener.

The buffer itself does not have any sense of time. When time jumps backwards the data must be cleared. using the `clear()` method like: https://github.com/ros/geometry2/blob/acb62b82726d3368549c6b519dda5d535557506c/tf2_ros/src/transform_listener.cpp#L102-L109

**Comment by svenlr** [comment]
Hello,
we have wrapped all our transform buffers in transform listeners and nevertheless experience a similar issue on ROS melodic with `rosbag play --clock --loop` and use_sim_time set to true. Warnings similar to the one below usually start to fill the console when the bag is repeated for the first time. However, it appears that there is about a small chance for a bag repetition without problems.

```
Warning: TF_OLD_DATA ignoring data from the past for frame base_link at time 1.54928e+09 according to authority /odometry
Possible reasons are listed at http://wiki.ros.org/tf/Errors%20explained
         at line 277 in /tmp/binarydeb/ros-melodic-tf2-0.6.5/src/buffer_core.cpp
```

Accompanying these errors, the `lookup_transform` calls in a node always failed. This could be "fixed" by checking for negative time difference and a consecutive manual `buffer.clear()`. Before applying the workaround, again, there was a small chance for a bag loop without problems.  
The above warning messages continue to appear despite the workaround. However, it is hard to tell what is producing them as there is no such information in them.

**Comment by pryre** [comment]
I'm not sure if this will assist too much @svenlr (or others), but for me, the issue was self-induced, as I was pushing my own data into the buffer manually in a timer function for visualization. The following code may help with your issues:

My timer function that pushes in custom data (see `check_update_time()` at the start: [here](https://github.com/pryre/mantis/blob/master/mantis_kinematics/src/mantis_kinematics/forward_kinematics.cpp#L162).

The `check_update_time()` [function](https://github.com/pryre/mantis/blob/master/mantis_kinematics/src/mantis_kinematics/forward_kinematics.cpp#L345) and "resetting" [function](https://github.com/pryre/mantis/blob/master/mantis_kinematics/src/mantis_kinematics/forward_kinematics.cpp#L337).
